services:
   - type: web
     name: your-service-name
     env: static
     buildCommand: npm run build
     staticPublishPath: build
     routes:
        - type: rewrite
          source: "/*"
          destination: "/index.html"
